name: Server Publish

on:
  release:
    types: created
    paths:
      - 'packages/drawio-mcp-server/**'
      - '.github/workflows/server-publish.yml'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "23.x"
          registry-url: "https://registry.npmjs.org"
          cache: "pnpm"
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install

      - name: Build plugin
        run: pnpm --filter drawio-mcp-plugin run build

      - name: Build
        run: pnpm --filter drawio-mcp-server run build

      - name: Publish
        run: npm publish --workspace=drawio-mcp-server --provenance --access public
